
python    run_xception.py  --model_path None   --data_path /sda2/imagenettfrecord/tfrecord_299/train_tf_299  --output_path  ./model_save3  --do_train True  --image_num  50000 --class_num  1000  --batch_size  64  --epoch  10 --learning_rate  0.001   --save_checkpoints_steps  10

          